### ISSUE TITLE
Is Bayer data mianly used for color alignment/HDR/denosing purpose? 

### ISSUE THREAD

**Issue by tachikoma777** [princeton-computational-imaging/NeuLS#1]
How does it work for JPG images after CCM/HDR/denosing, regardless of the color difference in final result

**Comment by Ilya-Muromets** [comment]
If I'm interpreting this correctly, are you asking whether it's possible to perform reconstruction with processed RGB data?

If so, probably yes, but you'd still need metadata in the form of intrinsics and initial camera rotations (gyro).

I don't think there's anything that makes Bayer data special, but since I was already collecting raw metadata off the phone, I decided I may as well use the highest resolution/bit-depth data available.
